### ISSUE TITLE
Update for version 0.8

### ISSUE THREAD

**Issue by mivade** [conda-forge/datrie-feedstock#2]
datrie was updated about a month ago on PyPI (https://github.com/pytries/datrie/issues/68) to work with Python 3.7 (which is over a year old now). This feedstock needs an update so tools that depend on it (e.g., Snakemake) can be used with Python 3.7 through a conda installation.

**Comment by mivade** [comment]
Related to #1.

**Comment by melund** [comment]
Thanks for pointing it out. Snakemake was the exact reason I added datrie to conda-forge in the first place. Just haven't used snakemake for a while. So I didn't notice. 

I have merged the newest version now.

**Comment by mivade** [comment]
Thanks!
